### ISSUE TITLE
Does this code work in Python 3?

### ISSUE THREAD

**Issue by sadmicrowave** [sadmicrowave/Resume-Ranker#5]
Will this code be effective and work in Python 3 without any refactoring?

**Comment by sadmicrowave** [comment]
the compatible python3 module for `pyPdf` produces an error on execution.  

`Traceback (most recent call last):
  File "ranker.py", line 36, in <module>
    import os, pyPdf, csv
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyPdf/__init__.py", line 1, in <module>
    from pdf import PdfFileReader, PdfFileWriter
ImportError: No module named 'pdf'`

**Comment by sadmicrowave** [comment]
This has been resolved in commit: e8dc1f0
